##################################
# $Id: Makefile,v 1.1 2004/05/11 14:57:50 jonnymind Exp $
#
# Makefile for XWT library
#

TARGET=libxwt.a

PRGFLAGS=-I../include
CFLAGS+=-I../include
XWT_INSTALL=../lib

CSOURCES=xwt_api.c

include ../Rules.make
