##################################
# $Id: Makefile,v 1.2 2004/05/17 02:55:40 lculik Exp $
#
# Makefile for XWT GTK interface
#

TARGET=libxwt_gtk.a
CFLAGS+=-I. -I../include `pkg-config --cflags gtk+-2.0` -fms-extensions

SOURCE_TYPE=c
XWT_INSTALL=../lib

include ../Rules.make
