#
# $Id: Makefile,v 1.1 2004/01/02 17:13:58 rodrigo_moreno Exp $
#

ifeq ($(HB_MAIN),)
 HB_MAIN = std
endif

ROOT = ../../../

CONTRIBS=\
        postgres \

PRG_SOURCES=\
        test.prg \

PRG_MAIN=\
	test.prg

LIBS=\
        debug \
        vm \
        rtl \
        lang \
        rdd \
        rtl \
        vm \
        macro \
        common \
	pq \

include $(TOP)$(ROOT)config/bin.cf

